// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermercadoAntojitos.Contexto.Api;

namespace SupermercadoAntojitos.Api.Migrations
{
    [DbContext(typeof(ServiceContext))]
    partial class ServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SupermercadoAntojitos.Entities.Api.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("UnidadesExistentes")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("ValorProducto")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id")
                        .HasName("PK__PRODUCTO__4BD51FA53F029E7A");

                    b.HasIndex("IdVenta");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entities.Api.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("UnidadesPorProducto")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("ValorPagar")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id")
                        .HasName("PK__VENTA__4BD51FA53F029E7A");

                    b.HasIndex("IdCliente");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entitiess.Api.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("DocumentoIdentidad")
                        .HasColumnType("numeric(18,0)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__CLIENTE__4BD51FA53F029E7A");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entities.Api.Producto", b =>
                {
                    b.HasOne("SupermercadoAntojitos.Entities.Api.Venta", "Ventas")
                        .WithMany("Productos")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entities.Api.Venta", b =>
                {
                    b.HasOne("SupermercadoAntojitos.Entitiess.Api.Cliente", "Clientes")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entities.Api.Venta", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SupermercadoAntojitos.Entitiess.Api.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
